// src/ui/footer.tsx
const now = new Date()
const year = now.getFullYear()

/**
 * Shows a footer at the bottom of the screen.
 */
export default function Footer() {
  return <div className='flex absolute bottom-0 w-full h-8 items-center px-2'>
    <span className='text-white text-shadow shadow-black'>Kyle Chapman, { year }</span>
  </div>
}

// src/components/Footer.vue
<template>
  <v-footer class="font-weight-medium" absolute padless>
    <v-col class="text-center" cols="12">
      Copyright &copy; {{ new Date().getFullYear() }} - Kyle Chapman
    </v-col>
  </v-footer>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "Footer"
});
</script>

<style scoped></style>
